### ISSUE TITLE
Canonical Naming

### ISSUE THREAD

**Issue by virtualritz** [killercup/materialx#1]
I just stumbled over this in my stream. Very interesting! Especially the parser. :sunglasses: 

While looking at the source I noticed naming is not canonical. 

E.g. `Node::ASin` should be `Node::Asin`.

See [Casing conforms to RFC 430 (C-CASE)](https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case).

**Comment by killercup** [comment]
Fun that you found this! The naming is quite ad-hoc, I haven't put much thought into it. It'll get better :)
